# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Angular-Cli

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4.0.1
      - name: Install deps
        run: npm i
      - name: Build app
        run: npm run build:prod
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}          
        
        
      
      
 
